### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tushar-dadlani**
Updated the path to point to the correct location of garden.

### CODE REVIEW

**Comment by tsaleh** [comment]
Hey Tushar - [kinda looks like you're a pivot](https://www.linkedin.com/in/tushardadlani)?  If so, can you have your account added to the pivotal org, and update your avatar to show an accurate picture of yourself?

**Comment by ematpl** [comment]
Hi, @tushar-dadlani,

You're also already a member of the cloudfoundry GitHub org, so if you [publicize your membership](https://help.github.com/articles/publicizing-or-concealing-organization-membership/) in that org, Dreddbot will recognize that you're covered by the CF organization CLA.

Best,
Eric

**Comment by tushar-dadlani** [comment]
Hi,

I have publicized my membership and have updated my github with an avatar.
Thanks for the inputs.

Best,
Tushar

On Thu, Mar 19, 2015 at 7:45 AM, Eric Malm <notifications@github.com> wrote:

> Hi, @tushar-dadlani <https://github.com/tushar-dadlani>,
>
> You're also already a member of the cloudfoundry GitHub org, so if you publicize
> your membership
> <https://help.github.com/articles/publicizing-or-concealing-organization-membership/>
> in that org, Dreddbot will recognize that you're covered by the CF
> organization CLA.
>
> Best,
> Eric
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-incubator/garden/pull/29#issuecomment-83613102>
> .
>



-- 
- Tushar Dadlani
   CloudOps at CF

**Comment by tsaleh** [comment]
Thanks Tushar!

**Pull request merged**
