### PR TITLE
better error message when failing to fetch docker image

### PR DESCRIPTION
**Pull request by irfanurrehman**
referring this PR in garden-linux
https://github.com/cloudfoundry-incubator/garden-linux/pull/35

### CODE REVIEW

**Comment by glyn** [comment]
Thanks for this. We'd like some tests of the new code. Please could you add them?

**Comment by irfanurrehman** [comment]
@glyn, updated the tests. please let me know if they seem to be ok !

**Comment by glyn** [comment]
The tests look ok to me. Thanks.

**Comment by irfanurrehman** [comment]
@glyn, had to update some things based on @julz comments.
Submitted the changes here too.
Please let me know if anything further is needed.
If everything is ok and you say so, I can squash all the changes into 1 commit.

**Comment by glyn** [comment]
Once you've absorbed Julz's suggestions, squash away.

**Comment by irfanurrehman** [comment]
done !!

also @glyn i saw couple of other stories on similar lines. I would be willing to submit PRs for them too. Am hoping, its Ok to do so!

**Comment by glyn** [comment]
@irfanurrehman absolutely and looking forward to more PRs from you!

**Comment by glyn** [comment]
I'm looking to merge this, but on reflection, I don't think HTTP 412 is appropriate in this situation. [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) defined 412 as
```
The precondition given in one or more of the request-header fields evaluated to false when it was tested on the server. This response code allows the client to place preconditions on the current resource metainformation (header field data) and thus prevent the requested method from being applied to a resource other than the one intended.
``` 
In this case, the error is unrelated to request-header fields. Furthermore, the error is not client-side, but server-side, so 5xx might be more appropriate. Unfortunately, only 500 seems to match this error. Therefore it would be better to send 500 with an indication of the error type in the body.

**Comment by irfanurrehman** [comment]
Hi Glyn, Sorry to have missed your comment day before yesterday; I did however see the code that u updated. The reason, I used 412 was its fairly rare to encounter, and I did not want to introduce own code in http(I might support that thought though for garden specific errors). 
What u updated now seems to best solve the current problem, with one catch that if garden server really gets into a http specific 503 situation (for any other scenario), the http error code would still be dropped from the error information returned at the client.
While implementing this, I did also think about a possible way of implementing garden specific error information in the http body (for example an additional info in json body) but then all other api calls ideally should also implement it, which I am not sure is needed as of now. 
Thanks anyways again for the updates.. :-)

**Comment by glestaris** [comment]
Thank you @irfanurrehman!

**Comment by glyn** [comment]
Good point, but if we hit a "genuine" 503, at least it will produce a ServiceUnavailableError, which should be a decent clue.

**Pull request merged**
