### PR TITLE
Adding network statistics to container metrics

### PR DESCRIPTION
**Pull request by shashidharatd**

### CODE REVIEW

**Comment by goonzoid** [comment]
Paired with https://github.com/cloudfoundry-incubator/garden-linux/pull/38

**Comment by glyn** [comment]
Please note that the Greenhouse team (garden-windows) will probably need to take a look at this so that can assess how Linux-specific the new stats are.

**Comment by dgoddard** [comment]
Hi, as far as Greenhouse these seem very generic. We are not sure if we (windows) can get anything other than bytes, but the concepts seem generic.

Thanks for the heads up

**Comment by shashidharatd** [comment]
To keep network statistics generic, kept only RrBytes, TxBytes and removed other stats.

**Pull request merged**
